import { defineConfig } from "@/lib/config";

// Private clone configuration - generated by setup script
const useCloneBranding = true;

export default defineConfig({
  // Branding - your organization's identity
  branding: {
    name: "agents-library",
    logo: "/logo.svg",
    logoDark: "/logo.svg",
    favicon: "/logo.svg",
    description: "Collect, organize, and share AI prompts",
  },

  // Theme - design system configuration
  theme: {
    radius: "sm",
    variant: "brutal",
    density: "default",
    colors: {
      primary: "#6366f1",
    },
  },

  // Authentication plugins
  auth: {
    providers: ["credentials"],
    allowRegistration: true,
  },

  // Internationalization
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },

  // Features
  features: {
    privatePrompts: true,
    changeRequests: true,
    categories: true,
    tags: true,
    comments: true,
    aiSearch: false,
    aiGeneration: false,
    mcp: false,
  },

  // Homepage customization (clone branding mode)
  homepage: {
    useCloneBranding,
    achievements: {
      enabled: false, // Disabled for private clones
    },
    sponsors: {
      enabled: true,
      items: [
        { name: "bl1nkos", logo: "/sponsors/acme.svg", url: "https:bl1nk.site" }
      ],
    },
  },
});
