#!/bin/bash
set -e

# Python 3.12
sudo apt-get update -y && sudo apt-get install -y python3.12 python3.12-pip python3.12-venv

# Python tools
pip3.12 install uv modal fastapi uvicorn

# Node tools
npm install -g pnpm
curl -fsSL https://bun.sh/install | bash

# Rust + Tauri
curl https://sh.rustup.rs -sSf | sh -s -- -y
source "$HOME/.cargo/env"
cargo install tauri-cli --version "^2"